path:
  config: config
  original_data: data/all_data
  processed_data: data/processed_data
  trained_model: model

# 是否进行特征提取
featured_extract: True

ml_parameters:
  # batch_size的大小并不会影响效率，但是会爆内存
  # 多线程数 
  n_job: 4
  # 基于tsfresh采样特征股票的数目
  sample_num: 2000
  # 滑动窗口构建的训练数据，每个股票采样的时间序列数目
  sample_ts_num: 50
  # tsfresh batch_size
  sample_batch_size: 200
  # sample_rate
  sample_rate: 0.9

  # train_data batch
  train_batch: 200

  # 观看历史天数
  look_back: 20
  # 预测后几天的和
  look_up: 5
  train_split: 0.9

  original_features: ['volume', 'turn', 'pctChg', 'pctRange', 'peTTM', 'pbMRQ', 'psTTM', 'pcfNcfTTM']


